name: Makefile CI

on:
  push:
    branches: [ "gcc" ]
  pull_request:
    branches: [ "gcc" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - run: sudo apt update -y
    - run: sudo apt-get install git fakeroot bc kmod cpio build-essential libarchive-dev  libarchive-tools libncurses5-dev ncurses-dev xz-utils dwarves   libssl-dev bc flex libelf-dev bison llvm libncurses-dev gawk flex bison openssl dkms libelf-dev libudev-dev libpci-dev clang lld libiberty-dev autoconf -y
    - run: git submodule update --init --recursive
    - run: make -j $(nproc) bindeb-pkg
    - run: mkdir tar.dir
    - run: mv *.deb tar.dir/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
               name: workflow.tar.xz
               path: ./tar.dir/
